### ISSUE TITLE
Timing of Z80 instructions

### ISSUE THREAD

**Issue by SapphiRe-MSX** [CollectorVision/Phoenix-Colecovision#12]
Coleco's (and MSX's) Z80 adds an extra cycle to all instructions for each memory access. That means some instructions have one or two extra cycles, depending on how many memory accesses do the instruction.

For instance, NOP instruction is 4 cycles, but on Coleco it must be 5 cycles. An example of instruction that adds two extra cycles is DEC (IX+o), that access two times to memory: one to obtain offset o and another one to decrement the content of IX+o. So the correct timing of this instruction should be 25 cycles instead of 23. A full detailed table of correct timing can be found on:

http://map.grauw.nl/resources/z80instr.php

If this is not correctly implemented, every code cycle-synchronized will fail. For instance sample voice players will play voices faster than expected (and distorted).

On QBIQS we have two examples of cycle-synchronized code: voice sample of GAME OVER and NTSC/PAL detection. Both of them works flawlesly on a real Coleco, but not on the Phoenix.

I suspect that the Z80 instrucions on Phoenix have an incorrect timing assigned.

**Comment by CollectorVision** [comment]
This was actually an issue with the AY SGM sound. This issue has been resolved in core revision 6.
