### ISSUE TITLE
F18A flicker/scanlines new menu issues

### ISSUE THREAD

**Issue by ikrananka** [CollectorVision/Phoenix-Colecovision#13]
The core update on 11/13/19 introduced a new menu to select flicker & scanlines settings.  There are a few issues with this new menu:

1. Pressing the keypad buttons 1 or 2 to toggle the settings will sometimes result in the setting being toggled twice, i.e. back to its original setting.  I tested this on three different original ColecoVision controllers and both of my Phoenix's.  It happens frequently enough to be irritating.

2. It is possible to get confused with the flicker status when making changes at the SD loader menu.  You can toggle the flicker to ON (press 2) and then exit (press 9).  Now say you've changed your mind and you press * again to access the menu - it now show the flicker as being OFF (even though you just set it to ON).  Okay, so I really wanted it OFF, it's displaying OFF, so now I'll just exit by pressing 9.  The problem is that if I now play a game the flicker is actually still set to ON even though it was displayed as being OFF.

**Comment by CollectorVision** [comment]
This should be resolved with core revision 6
