### ISSUE TITLE
Wizard of Wor ROM via SD card not working (core v6)

### ISSUE THREAD

**Issue by ikrananka** [CollectorVision/Phoenix-Colecovision#14]
Wizard of Wor works fine if played from the original cart or with the game ROM using an AtariMax Ultimate SD.  However, it does not work if trying to play from an SD card inserted into the Phoenix.  Upon loading the game a white screen is displayed quickly followed by the screen going black.  No sounds are heard.

**Comment by CollectorVision** [comment]
Modified rom that works is in the thread on AA where Pixelboy released WoW rom.

**Comment by ikrananka** [comment]
Here's the link to the file location:

https://atariage.com/forums/topic/299910-team-pixelboy-news-bulletin-december-25th-2019/?do=findComment&comment=4418318
