### ISSUE TITLE
Sidney works fine, but no other games work and SD card isn’t working 

### ISSUE THREAD

**Issue by mfeldsher** [CollectorVision/Phoenix-Colecovision#15]
Sidney cart work fine in my Phoenix, but that’s it. The SD card isn’t working. It worked once and that’s it. I loaded more roms on it. I don’t know if that’s the issue. 
Sidney is the only cart that is working. Smurfs, turbo etc isn’t working. 
Does anyone have any ideas.

**Comment by CollectorVision** [comment]
What specifically is it doing when it doesn't work? Did you see the issue
with the system not powering down all the way?

Are you using the sd card that came with it? If not, did you format the sd
card to FAT32?

**Comment by mfeldsher** [comment]
I switched powered off the Tv, and switched the HDMI cable. Monoprice Select Series High Speed HDMI Cable - 4K@60Hz HDR 18Gbps YCbCr 4:4:4 28AWG, 10ft, Yellow. 
My TV is a Sony Bravia 75” 2017. 
When I switched the TV to a small 13”  cheapy TV it worked fine. 
Does any have any suggestions on maybe a filter or switch I could use to get it to work on a Sony Bravia 75”.
I know it won’t be displayed on the tv and there will be a lot of black, but I’d rather still use it on this TV
![13DA5ED4-824E-4844-BA70-CE52C02937F4](https://user-images.githubusercontent.com/58125954/69488972-b9229000-0e3f-11ea-934a-72161a383c77.jpeg)

**Comment by lilalien** [comment]
The Phoenix has known issues with Sony Bravia TVs, including my 40" from 2 years ago...

I believe this is being looked at. I have to temporarily use a 20" Vizio I also have in my game room with the Phoenix. Most of the time the TV just reports the signal isn't supported or something like that and I don't even get a picture.

**Comment by mfeldsher** [comment]
> Sidney cart work fine in my Phoenix, but that’s it. The SD card isn’t working. It worked once and that’s it. I loaded more roms on it. I don’t know if that’s the issue.
> Sidney is the only cart that is working. Smurfs, turbo etc isn’t working.
> Does anyone have any ideas.



> Sidney cart work fine in my Phoenix, but that’s it. The SD card isn’t working. It worked once and that’s it. I loaded more roms on it. I don’t know if that’s the issue.
> Sidney is the only cart that is working. Smurfs, turbo etc isn’t working.
> Does anyone have any ideas.

I got the converter on amazon and it works like a charm now. I’m super satisfied 
https://www.amazon.com/dp/B01N06Q9WH/ref=cm_sw_r_other_apa_i_aCzWDb2K5MSPS?fbclid=IwAR3_FS451QnGLA7EVdREomQLkzTvgcq9UikPLUqqfXiqS_6M7jkYN8FFOoc
