### ISSUE TITLE
Music issue with some games

### ISSUE THREAD

**Issue by ghost** [CollectorVision/Phoenix-Colecovision#16]
Having a sound issue with some games. The sound coming out is glitchy and buzzy for specific part of the game. It is not as smooth as playing it with original Colecovision.

Here are videos sample.

Cosmic Avenger: Initial music at the beginning of the game.
https://youtu.be/wGUExt2GF7o

Frogger: The initial music. I tried both cartridge and rom and they are the same. 
https://youtu.be/QTA-COU3BZg

**Comment by ikrananka** [comment]
Have you updated the ColecoVision core to version 6?  There are some significant audio issues addressed with this release.

**Comment by ghost** [comment]
Working with latest core update
