### ISSUE TITLE
Some early Opcode Game releases do not work (core v6)

### ISSUE THREAD

**Issue by ikrananka** [CollectorVision/Phoenix-Colecovision#18]
The following early Opcode Game releases do not work with either the original cart or with a ROM file:

* Road Fighter - Animated ColecoVision is displayed followed by static blue screen.
* Magical Tree - Displays blue screen with garbled coloured blocks in the middle.  If left long enough a partial ColecoVision logo is displayed and then moving garbled coloured blocks move around and the game music can be heard.
* Sky Jaguar - Displays a black screen with garbled coloured blocks that move up the screen which then changes to a series of narrow horizontal green lines.  If one waits long enough for the attract mode to restart (although you can't see this on-screen), then the Konami logo appears and the games then operates as normal with the attract mode appearing correctly on-screen.

Both Space Invaders Collection and Pac-Man Collection seem to work fine.

**Comment by lilalien** [comment]
I'll go through some additional opcode games I have and see if any crap out for me too...

**Comment by CollectorVision** [comment]
This is resolved in Rev7 of the core. Released 7/21/20
