### ISSUE TITLE
Problem with comic bakery

### ISSUE THREAD

**Issue by thunderrabbit007** [CollectorVision/Phoenix-Colecovision#19]
If I inserted my Comic Bakery Cartridge the screen is only black. 
The phoenix startscreen is visible. My other games are working correct 
Firmware v6

**Comment by ikrananka** [comment]
Is this the CollectorVision release?  I just tried my cart and the game started and played fine.  Perhaps try cleaning your cart contacts and see if that makes any difference.

**Comment by thunderrabbit007** [comment]
Cleaned the contacts and it worked
