### ISSUE TITLE
Cannot change F18A USR1 & USR2 settings with real cartridges

### ISSUE THREAD

**Issue by ikrananka** [CollectorVision/Phoenix-Colecovision#2]
While it is currently possible to change the F18A USR1 (4 or 32 sprites) and USR2 (scan lines) setting using the # and * keys on a CV controller keypad, this is only possible when the SD loader menu is displayed.  If a ColecoVision cartridge is inserted into the Phoenix (including the AtariMax) there is current means to change the USR1 and USR2 settings.

As the default USR1 setting is 32 sprites ("no flicker") this means that for real cartridges sprite masking does not work and so, for example, all of Penta the penguin's body is visible when falling into a crevasses when instead the bottom half should be hidden (masked).

**Comment by CollectorVision** [comment]
If the game boots to the normal CV menu you can actually set these on the game. If using atarimax, select the game then hit the reset button. While the Phoenix logo is displayed you can change the sprite flicker and scanline settings.

Unfortunately for Antarctic Adventure the game boots straight to the game (even though it looks like it goes through the bios, the first screen is actually part of the game not the BIOS), so the sprite flicker and scanlines can't be changed.

We are looking into enhancing this to make the setting persistent at a later date.

**Comment by ikrananka** [comment]
That's great to know.  Yes, a persistent setting makes perfect sense and glad it's planned for a later date.

BTW - loving the Phoenix so far - thanks to the entire team for bringing this to us and for your ongoing endeavours

**Comment by lilalien** [comment]
I'd love the persistent option for flicker and scanlines!

**Comment by CollectorVision** [comment]
Fixed with core update on 11/13/19
Hold * or # on core loading or reset to get to menu where flicker/scanlines can be set.
