### ISSUE TITLE
updating service core break menu

### ISSUE THREAD

**Issue by haightc** [CollectorVision/Phoenix-Colecovision#26]
After updating service core, no option to enter core menu is available

**Comment by CollectorVision** [comment]
The service core installed was not supported by the new hardware. The shipped version has fixes for a change in video output.

The service menu still works but will need to be operated blind. Load the service menu for the production run 2 onto the sd card and then turn on the system and immediately press # and then 3. This will install the service menu on the sd card and the LED will flash pink while updating. Once it turns back to green you can power cycle the system and it should be resolved
[SERVICE.zip](https://github.com/CollectorVision/Phoenix-Colecovision/files/6373568/SERVICE.zip)

**Comment by CollectorVision** [comment]
Make sure to unzip the service menu to the root core of the sd card. This is only necessary for a production run 2 Phoenix where the service menu was manually "updated" with the old version. There is no benefit to installing this on a production run 1 system.

**Comment by haightc** [comment]
nothing happens when I do this, the light just stays green

________________________________
