### ISSUE TITLE
Odd menu display issues with Atarimax Ultimate SD Multicart

### ISSUE THREAD

**Issue by lilalien** [CollectorVision/Phoenix-Colecovision#7]
So I've noticed quite a few menu display issues using the Coleco core.

Just browsing through tons of alphabetical folders on the multicart (which displays perfectly on a real Colecovision), a lot of screen issues occur. Lots of artifacts appear as you scroll the joystick around, and it gets worse and worse and at times its completely unreadable.

When I can read the screen at times, clicking and loading a game has no issue. Though I will be posting bug reports for sound issues in various Colecovision games I've noticed. :)

The picture quality is wonderful! Kudos to the whole crew!

**Comment by CollectorVision** [comment]
Can you provide some pictures or video of what you are seeing? Which multicart are you using?

**Comment by lilalien** [comment]
I’m using the Atarimax Ultimate SD for Colecovision... Same cart and games I use in my Colecovision.

As for screenshots or video, I can definitely do that tomorrow to help track down the issues!

I’m having such a blast with it!

**Comment by lilalien** [comment]
Hmm can’t post videos only still photos here? I attached a couple screenshots but I have tons of videos now of all my reported bugs. Where should I include them?

**Comment by lilalien** [comment]
![1D3B30E5-B076-477E-8881-FBA88A44215C](https://user-images.githubusercontent.com/35111972/68234936-4f496000-ffd0-11e9-950f-b64913340a89.jpeg)
![341A2F43-DB6A-4746-8D4A-62484F6A7C33](https://user-images.githubusercontent.com/35111972/68234937-4f496000-ffd0-11e9-8418-117308c44cff.jpeg)

**Comment by lilalien** [comment]
Want to eliminate the obvious as well. Cart pins are cleaned and work perfectly on a real Colecovision.

**Comment by CollectorVision** [comment]
Easiest thing for videos is to upload to youtube and then post a link here. That is strange, I have used my atarimax almost daily and have never seen those issues.

**Comment by lilalien** [comment]
Example video:

https://youtu.be/uTePHH7iaso

**Comment by lilalien** [comment]
Example video 2:

https://youtu.be/MZz1Nfxtfl4

**Comment by lilalien** [comment]
So I've updated my Atarimax multicart to the latest 2019 beta, and I haven't seen a menu issue yet (after about 15 minutes). I'll let you know should the glitches return with the multicart!

**Comment by CollectorVision** [comment]
I'll mark this closed then. If it comes back let me know and I will re-open it.
